name: aseprite
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/aseprite.yaml
env:
  BUILD_TYPE: RelWithDebInfo
  TARGET_DIR: build
jobs:
  aseprite:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'aseprite/aseprite'
        submodules: 'recursive'

    - name: Cache Aseprite
      id: cache-aseprite
      uses: actions/cache@v3
      with:
        path: aseprite
        key: ${{ runner.os }}-aseprite

    - uses: turtlesec-no/get-ninja@main
    - name: Install Dependencies
      shell: bash
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y \
          libx11-dev libxcursor-dev libxi-dev
    - name: Generating Makefiles
      shell: bash
      run: |
        cmake -S . -B ${{ env.TARGET_DIR }} -G Ninja \
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
          -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 \
          -DENABLE_TESTS=off \
          -DENABLE_UI=off \
          -DENABLE_CCACHE=off
    - name: Compiling
      shell: bash
      run: |
        cd ${{ env.TARGET_DIR }} && ninja
    - name: Move executable for cache
      run: |
        mkdir aseprite
        mv ${{ env.TARGET_DIR }}/bin/aseprite ./aseprite/
        mv ${{ env.TARGET_DIR }}/bin/data ./aseprite/

