name: wasm-build-deploy

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - .github/workflows/aseprite.yaml
    branches:
      - release
    tags:
      - 'v*'
env:
  BUILD_DIR: build
  WEB_DIR: build/web
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        lfs: true
    - name: Setup Go
      id: setup-go
      uses: actions/setup-go@v4
      with:
        go-version-file: "go.mod"
        cache-dependency-path: "**/*.sum"
    - name: Cache Aseprite
      id: cache-aseprite
      uses: actions/cache@v3
      with:
        path: aseprite
        key: ${{ runner.os }}-aseprite

    - name: Setup Ninja for Aseprite
      uses: turtlesec-no/get-ninja@main
      if: steps.cache-aseprite.outputs.cache-hit != 'true' || steps.setup-go.outputs.cache-hit != 'true'
    - name: Install Aseprite/Ebitengine Dependencies
      if: steps.cache-aseprite.outputs.cache-hit != 'true' || steps.setup-go.outputs.cache-hit != 'true'
      shell: bash
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y \
          libx11-dev libxcursor-dev libxi-dev
    - name: Build Github Pages
      run: make web
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2.0.0
      with:
        path: ./${{ env.WEB_DIR }}
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2.0.4
