name: wasm-build-deploy
#Current runner version: '2.309.0'
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - .github/workflows/aseprite.yaml
    branches:
      - release
    tags:
      - 'v*'
env:
  BUILD_DIR: build
  WEB_DIR: build/web
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DISPLAY: ':99.0'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup Go
        id: setup-go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
          cache-dependency-path: "**/*.sum"
      - name: Cache Aseprite
        id: cache-aseprite
        uses: actions/cache@v3
        with:
          path: aseprite
          key: ${{ runner.os }}-aseprite
      - name: Install Aseprite Dependencies
        if: steps.cache-aseprite.outputs.cache-hit != 'true'
        shell: bash
        run: |
          sudo apt-get update -qq
          sudo apt-get install --no-install-recommends -y \
            libx11-dev libxcursor-dev libxi-dev \
            ninja-build
      - name: Build Aseprite
        if: steps.cache-aseprite.outputs.cache-hit != 'true'
        shell: bash
        run: |
          make aseprite/aseprite

      - name: Install Ebiten Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -qq
          sudo apt-get --no-install-recommends -y \
            install libasound2-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev
      - name: Setup display needed for GLFW to build
        if: runner.os == 'Linux'
        run: |
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - name: Build Github Pages
        run: make web
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2.0.0
        with:
          path: ./${{ env.WEB_DIR }}
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3.0.1
